/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_sistemi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author uset
 */
public class araba_guncelleme extends javax.swing.JFrame {

    /**
     * Creates new form araba_guncelleme
     */
    public araba_guncelleme() {
        this.setResizable(false);
        this.setLocation(750, 450);
        this.setTitle("ARABA GÜNCELLEME");
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        araba_id = new javax.swing.JTextField();
        araba_marka = new javax.swing.JButton();
        araba_model = new javax.swing.JButton();
        vites_turu = new javax.swing.JButton();
        yakit_turu = new javax.swing.JButton();
        rengi = new javax.swing.JButton();
        bir_onceki = new javax.swing.JButton();
        cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Araba ID :");

        araba_marka.setText("Marka");
        araba_marka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araba_markaActionPerformed(evt);
            }
        });

        araba_model.setText("Model");
        araba_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araba_modelActionPerformed(evt);
            }
        });

        vites_turu.setText("Vites Türü ID");
        vites_turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vites_turuActionPerformed(evt);
            }
        });

        yakit_turu.setText("Yakıt Türü ID");
        yakit_turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakit_turuActionPerformed(evt);
            }
        });

        rengi.setText("Renk ID");
        rengi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rengiActionPerformed(evt);
            }
        });

        bir_onceki.setText("Bir Önceki Menü");
        bir_onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_oncekiActionPerformed(evt);
            }
        });

        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(araba_id, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vites_turu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(araba_marka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(araba_model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yakit_turu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(rengi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bir_onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(araba_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(araba_marka)
                    .addComponent(araba_model))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vites_turu)
                    .addComponent(yakit_turu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rengi)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bir_onceki)
                    .addComponent(cikis))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araba_markaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araba_markaActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = araba_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("araba_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String marka = JOptionPane.showInputDialog(null,"ARABA MARKA");
                bg.myStat.executeUpdate("update araba set araba_marka='"+marka+"' where araba_ID="+ID);
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba Marka güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı araba bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_araba_markaActionPerformed

    private void araba_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araba_modelActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = araba_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("araba_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String model = JOptionPane.showInputDialog(null,"ARABA MODEL");
                bg.myStat.executeUpdate("update araba set araba_model='"+model+"' where araba_ID="+ID);
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba Model güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı araba bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_araba_modelActionPerformed

    private void vites_turuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vites_turuActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0,kontrol2=0;
        String ID = araba_id.getText();
        String vites = "";
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("araba_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                vites = JOptionPane.showInputDialog(null,"ARABA VİTES TÜRÜ");
            
                bg.myRs = bg.myStat.executeQuery("select * from vites");
                while(bg.myRs.next()) {
                    if(bg.myRs.getString("vitesturu_ID").equalsIgnoreCase(vites)){
                        kontrol2=1;
                        break;
                    }
                }
                
                if(kontrol2==0){
                    JOptionPane.showMessageDialog(null,"'"+vites+"' ID numaralı vites türü bulunmamaktadır.");
                }
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı araba bulunmamaktadır");
            
            if(kontrol==1 && kontrol2==1){
                
                bg.myStat.executeUpdate("update araba set araba_vitesturuid='"+vites+"' where araba_ID="+ID);
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba Vites Türü güncellendi");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vites_turuActionPerformed

    private void yakit_turuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakit_turuActionPerformed
        baglanti bg = new baglanti();
        boolean kontrol=false,kontrol2=false;
        String ID = araba_id.getText();
        String yakit = "";
        
        try {
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            while(bg.myRs.next()){
                if(bg.myRs.getString("araba_id").equalsIgnoreCase(ID)){
                    kontrol=true;
                    
                    bg.myRs = bg.myStat.executeQuery("select * from yakit");
                    yakit = JOptionPane.showInputDialog(null,"YAKIT TÜRÜ ID");
                    while(bg.myRs.next()){
                        if(bg.myRs.getString("yakitturu_id").equalsIgnoreCase(yakit)){
                            kontrol2=true;
                            bg.myStat.executeUpdate("update araba set araba_yakitturuid='"+yakit+"' where araba_ID="+ID);
                            JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba Yakıt Türü güncellendi");
                            break;
                        }
                    }
                    
                    if(!kontrol2){
                        JOptionPane.showMessageDialog(null,"'"+yakit+"' ID numaralı Yakıt Türü bulunmamaktadır");
                    }
                    break;
                }
            }
            
            if(!kontrol){
               JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba bulunmamaktadır"); 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(araba_guncelleme.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_yakit_turuActionPerformed

    private void rengiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rengiActionPerformed
        baglanti bg = new baglanti();
        boolean kontrol=false,kontrol2=false;
        String ID = araba_id.getText();
        String renk = "";
        
        try {
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            while(bg.myRs.next()){
                if(bg.myRs.getString("araba_id").equalsIgnoreCase(ID)){
                    kontrol=true;
                    
                    bg.myRs = bg.myStat.executeQuery("select * from renkler");
                    renk = JOptionPane.showInputDialog(null,"RENK ID");
                    while(bg.myRs.next()){
                        if(bg.myRs.getString("renk_id").equalsIgnoreCase(renk)){
                            kontrol2=true;
                            bg.myStat.executeUpdate("update araba set araba_renkid='"+renk+"' where araba_ID="+ID);
                            JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba rengi güncellendi");
                            break;
                        }
                    }
                    
                    if(!kontrol2){
                        JOptionPane.showMessageDialog(null,"'"+renk+"' ID numaralı renk bulunmamaktadır");
                    }
                    break;
                }
            }
            
            if(!kontrol){
               JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı Araba bulunmamaktadır"); 
            }
           bg.myRs.close();
           bg.myStat.close(); 
        } catch (SQLException ex) {
            Logger.getLogger(araba_guncelleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rengiActionPerformed

    private void bir_oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_oncekiActionPerformed
        this.setVisible(false);
        kayit_guncelleme frame = new kayit_guncelleme();
    }//GEN-LAST:event_bir_oncekiActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(araba_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(araba_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(araba_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(araba_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new araba_guncelleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField araba_id;
    private javax.swing.JButton araba_marka;
    private javax.swing.JButton araba_model;
    private javax.swing.JButton bir_onceki;
    private javax.swing.JButton cikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rengi;
    private javax.swing.JButton vites_turu;
    private javax.swing.JButton yakit_turu;
    // End of variables declaration//GEN-END:variables
}
