/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_sistemi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author uset
 */
public class ilan_guncelleme extends javax.swing.JFrame {

    /**
     * Creates new form ilan_guncelleme
     */
    public ilan_guncelleme() {
        this.setResizable(false);
        this.setLocation(750, 450);
        this.setTitle("İLAN GÜNCELLEME");
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ilan_id = new javax.swing.JTextField();
        ilan_adi = new javax.swing.JButton();
        ilan_fiyat = new javax.swing.JButton();
        ilan_km = new javax.swing.JButton();
        ilan_tarih = new javax.swing.JButton();
        araba_id = new javax.swing.JButton();
        sehir_id = new javax.swing.JButton();
        bir_onceki = new javax.swing.JButton();
        cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("İlan ID :");

        ilan_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilan_idActionPerformed(evt);
            }
        });

        ilan_adi.setText("İlan Adı");
        ilan_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilan_adiActionPerformed(evt);
            }
        });

        ilan_fiyat.setText("İlan Fiyatı");
        ilan_fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilan_fiyatActionPerformed(evt);
            }
        });

        ilan_km.setText("İlan Km");
        ilan_km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilan_kmActionPerformed(evt);
            }
        });

        ilan_tarih.setText("İlan Tarihi");
        ilan_tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilan_tarihActionPerformed(evt);
            }
        });

        araba_id.setText("Araba ID");
        araba_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araba_idActionPerformed(evt);
            }
        });

        sehir_id.setText("Şehir ID");
        sehir_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehir_idActionPerformed(evt);
            }
        });

        bir_onceki.setText("Bir Önceki Menü");
        bir_onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_oncekiActionPerformed(evt);
            }
        });

        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ilan_id, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bir_onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(araba_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(ilan_km, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ilan_adi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sehir_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ilan_tarih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(ilan_fiyat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilan_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilan_adi)
                    .addComponent(ilan_fiyat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilan_km)
                    .addComponent(ilan_tarih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(araba_id)
                    .addComponent(sehir_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bir_onceki)
                    .addComponent(cikis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilan_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilan_idActionPerformed
        
    }//GEN-LAST:event_ilan_idActionPerformed

    private void ilan_tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilan_tarihActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String tarih = JOptionPane.showInputDialog(null,"İLAN KM");
                bg.myStat.executeUpdate("update ilan set ilan_tarih='"+tarih+"' where ilan_ID="+Integer.parseInt(ID));
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilan tarihi güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ilan_tarihActionPerformed

    private void ilan_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilan_adiActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String ad = JOptionPane.showInputDialog(null,"İLAN ADI");
                bg.myStat.executeUpdate("update ilan set ilan_adi='"+ad+"' where ilan_ID="+Integer.parseInt(ID));
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilan adı güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ilan_adiActionPerformed

    private void ilan_fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilan_fiyatActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String fiyat = JOptionPane.showInputDialog(null,"İLAN FİYATI");
                bg.myStat.executeUpdate("update ilan set ilan_fiyat="+fiyat+" where ilan_ID="+Integer.parseInt(ID));
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilan fiyatı güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ilan_fiyatActionPerformed

    private void ilan_kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilan_kmActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                String km = JOptionPane.showInputDialog(null,"İLAN KM");
                bg.myStat.executeUpdate("update ilan set ilan_km="+km+" where ilan_ID="+Integer.parseInt(ID));
                JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilan km güncellendi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ilan_kmActionPerformed

    private void araba_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araba_idActionPerformed
        baglanti bg = new baglanti();
        boolean kontrol=false,kontrol2=false;
        String a_id="";
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=true;
                    
                    a_id = JOptionPane.showInputDialog(null,"ARABA ID");
                
                    bg.myRs = bg.myStat.executeQuery("select * from araba");
                
                    while(bg.myRs.next()) {
                        if(bg.myRs.getString("araba_ID").equalsIgnoreCase(a_id)){
                            kontrol2=true;
                            bg.myStat.executeUpdate("update ilan set ilan_arabaid='"+a_id+"' where ilan_ID="+Integer.parseInt(ID));
                            JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilanın Araba ID güncellendi");
                            break;
                        }
                    }
                    
                    if(!kontrol2){
                        JOptionPane.showMessageDialog(null,"'"+a_id+"' numaralı araba bulunmamaktadır"); 
                    }
                    
                    break;
                }
            }
            
            if(!kontrol){
               JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır"); 
            }  
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_araba_idActionPerformed

    private void sehir_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehir_idActionPerformed
        baglanti bg = new baglanti();
        boolean kontrol=false,kontrol2=false;
        String s_id="";
        String ID = ilan_id.getText();
        
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=true;
                    
                    s_id = JOptionPane.showInputDialog(null,"ŞEHİR ID");
                
                    bg.myRs = bg.myStat.executeQuery("select * from sehirler");
                
                    while(bg.myRs.next()) {
                        if(bg.myRs.getString("sehir_ID").equalsIgnoreCase(s_id)){
                            kontrol2=true;
                            bg.myStat.executeUpdate("update ilan set ilan_sehirid='"+s_id+"' where ilan_ID="+Integer.parseInt(ID));
                            JOptionPane.showMessageDialog(null,"'"+ID+"' ID numaralı ilanın Şehir ID güncellendi");
                            break;
                        }
                    }
                    
                    if(!kontrol2){
                        JOptionPane.showMessageDialog(null,"'"+s_id+"' plakalı şehir bulunmamaktadır"); 
                    }
                    
                    break;
                }
            }
            
            if(!kontrol){
               JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır"); 
            }  
            bg.myRs.close();
            bg.myStat.close();
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sehir_idActionPerformed

    private void bir_oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_oncekiActionPerformed
        this.setVisible(false);
        kayit_guncelleme frame = new kayit_guncelleme();
    }//GEN-LAST:event_bir_oncekiActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ilan_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ilan_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ilan_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ilan_guncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ilan_guncelleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton araba_id;
    private javax.swing.JButton bir_onceki;
    private javax.swing.JButton cikis;
    private javax.swing.JButton ilan_adi;
    private javax.swing.JButton ilan_fiyat;
    private javax.swing.JTextField ilan_id;
    private javax.swing.JButton ilan_km;
    private javax.swing.JButton ilan_tarih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sehir_id;
    // End of variables declaration//GEN-END:variables
}
