/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_sistemi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author uset
 */
public class kayit_silme extends javax.swing.JFrame {

    /**
     * Creates new form kayit_silme
     */
    public kayit_silme() {
        this.setResizable(false);
        this.setLocation(750, 450);
        this.setTitle("KAYIT SİLME");
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ilan = new javax.swing.JButton();
        araba = new javax.swing.JButton();
        renk = new javax.swing.JButton();
        vites_turu = new javax.swing.JButton();
        yakit_turu = new javax.swing.JButton();
        sehir = new javax.swing.JButton();
        bir_onceki = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Silmek istediğiniz verinin ID numarasını girip ilgili butona basınız");

        ilan.setText("İlan");
        ilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilanActionPerformed(evt);
            }
        });

        araba.setText("Araba");
        araba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabaActionPerformed(evt);
            }
        });

        renk.setText("Renk");
        renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renkActionPerformed(evt);
            }
        });

        vites_turu.setText("Vites Türü");
        vites_turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vites_turuActionPerformed(evt);
            }
        });

        yakit_turu.setText("Yakıt Türü");
        yakit_turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakit_turuActionPerformed(evt);
            }
        });

        sehir.setText("Şehir");
        sehir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehirActionPerformed(evt);
            }
        });

        bir_onceki.setText("Bir Önceki Menü");
        bir_onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_oncekiActionPerformed(evt);
            }
        });

        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        jLabel2.setText("Veri ID :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(renk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yakit_turu)
                            .addComponent(bir_onceki)
                            .addComponent(ilan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vites_turu)
                                .addComponent(araba, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sehir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(araba)
                    .addComponent(ilan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renk)
                    .addComponent(vites_turu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sehir)
                    .addComponent(yakit_turu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bir_onceki)
                    .addComponent(cikis))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilanActionPerformed
        
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from ilan");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("ilan_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from ilan where ilan_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı ilan silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı ilan bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ilanActionPerformed

    private void arabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabaActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from araba");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("araba_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
                
                
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from araba where araba_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı araba silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı araba bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_arabaActionPerformed

    private void renkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renkActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from renkler");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("renk_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
                
                
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from renkler where renk_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı Renk silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı Renk bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_renkActionPerformed

    private void vites_turuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vites_turuActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from vites");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("vitesturu_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
                
                
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from vites where vitesturu_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı Vites Türü silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı Vites Türü bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vites_turuActionPerformed

    private void yakit_turuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakit_turuActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from yakit");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("yakitturu_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
                
                
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from yakit where yakitturu_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı Yakıt Türü silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı Yakıt Türü bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yakit_turuActionPerformed

    private void sehirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehirActionPerformed
        baglanti bg = new baglanti();
        int kontrol=0;
        String ID = id.getText();
        
        try {
            
            bg.myRs = bg.myStat.executeQuery("select * from sehirler");
            
            
            while(bg.myRs.next()) {
                if(bg.myRs.getString("sehir_ID").equalsIgnoreCase(ID)){
                    kontrol=1;
                    break;
                }
                
                
            }
            
            if(kontrol==1){
                bg.myStat.executeUpdate("delete from sehirler where sehir_ID="+ID);
                JOptionPane.showMessageDialog(null,ID+" ID numaralı Şehir silindi");
            }
            else
                JOptionPane.showMessageDialog(null,"'"+ID+"' numaralı Şehir bulunmamaktadır");
            
        } catch (SQLException ex) {
            Logger.getLogger(kayit_silme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sehirActionPerformed

    private void bir_oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_oncekiActionPerformed
        this.setVisible(false);
        veri_isleme frame = new veri_isleme();
    }//GEN-LAST:event_bir_oncekiActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayit_silme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayit_silme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayit_silme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayit_silme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayit_silme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton araba;
    private javax.swing.JButton bir_onceki;
    private javax.swing.JButton cikis;
    private javax.swing.JTextField id;
    private javax.swing.JButton ilan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton renk;
    private javax.swing.JButton sehir;
    private javax.swing.JButton vites_turu;
    private javax.swing.JButton yakit_turu;
    // End of variables declaration//GEN-END:variables
}
